export const ADD_REMINDER = 'ADD_REMINDER';
export const REMOVE_REMINDER = 'REMOVE_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';

export const SET_CALENDAR_MONTH = 'SET_CALENDAR_MONTH';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
